### ISSUE TITLE
Loose version constraint or doctrine/annotations

### ISSUE THREAD

**Issue by olafkarsten** [mintware-de/json-object-mapper#10]
Is there any reason to use such a strict version constraint for doctrine/annotations in composer.json? I wouldn't expect any problems from using ~1.4 instead of ~1.4.0?

It makes unnecessary hard to use a current version of e.g. doctrine/orm (requires >1.5)

**Comment by Devtronic** [comment]
No, there is no specific reason. At the time I released the package, 1.4 was the current version. If higher versions also work, feel free and create a pull request ;-) Otherwise I'll check that if I've more time than right now.
